services:
  - type: web
    name: pwfb-financial-potal-web
    runtime: node
    plan: free
    rootDir: web
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
